* различные мыли по поводу языка, некоторые куски кода демонстрирующие эти мысли.
В общем это поток сознания, тут я буду пытаться описать хоть как-то то, что я думаю о средствах выражения.
То есть не только языке программирования и уж точно не только его в виде естественного языка.
С этого момента в общем проект можно переименовывать из natural во что-то другое, но я подумаю ещё раз.
Просто потому, что конечная цель всё равно в естественном выражении мыслей человека, пусть и не в виде
ЯП, но и допустим диаграмм. Посмотрим.

** пример первый:
Нам нужно создать список. Пусть это будет список песен. Нечто вроде плейлиста. Не будем пока вникать как
это всё будет играться, эта тема ещё предстоит в рамках проекта caravan. Сейчас надо подумать над такой простой
вещью как список. Что нам нужно от него? Правильно:
+ сформировать
+ отобразить
+ передать
+ изменять

Вроде бы всё просто, но чтобы это сделать нужно кучу телодвижений сделать. Простой список в виде ui элементов
любого тулкита удовлетворяет только первым двум требованиям.
Однако если мы просто возьмём лист бумаги, составим на нём список и передадим его другому человеку - все пункты
реализуются. Значит ли что бумага проще? Да, во многих случаях. Она может то, что конечно можно сделать и в
компьютерном мире, с помощью скажем того же postscript. Но, попробуйте ка изменить произвольный pdf или ps,
когда получите! А поправить список на листке бумаги просто, даже не обязательно ручкой, хоть пальцем грязным.
Всё эти соображения здесь важны, чтобы не забыть о них, как забывают о них тысячи разработчиков, вновь и 
вновь изобретающих всякие material design и забывших почему gui в xerox разработали таким, каким разработали
и почему кнопка должна выглядеть как кнопка.
Итак, вернёмся к примеру. Как сделать так, чтобы всё это реализовать программно? Про нужно ли - это другой вопрос:)
Очевидно что нам нужен способ сформировать. И очевидно, что человек привык и это правильно - делать что-то 
руками, глазами, то есть работать с формой, это и значит сформировать. Использовать для этого всякие + для
начала элемента списка или даже перетаскивать элемент списка с панели инструментов - это не то, что человек
делает, это не то что вообще кто-либо или что-либо в этом мире делает. Да, так делает человек сегодня.
Но это неестественно. Так вот, 
+ сформировать - это
  визуально или мысленно взять и сформировать список из элементов последовательно
  Как мы это делаем на бумаге. Или как мы это делаем в голове, просто определив последовательность элементов,
  каким-то неведомым образом эти элементы объединив в итоге в группу и вуаля.
  Здесь важно понимать, что способ формирования зависит от иструментов. В голове одни инструменты, бумага - другие
  и уж очевидно, что на компьютере третьи. Зачем на компьютере мы делаем как на бумаге, но более примитивно?
  А как надо?  

+ отобразить - это
  Ну очевидно просто написовать на экране, компьютер же.
  И изображение должно быть таким, чтобы среднестатический житель планеты понял, что это список. Вот когда
  вы кладёте перед человеком одинаковые камешки в ряд, он же понимает? Вот и тут так надо. Словом в xerox parc
  это отчасти понимали, а другие просто слизали непоняв.
  
+ передать - это
  А вот тут уже непросто. Бумагу можно передать, потому что это предмет. Из головы список можно передать словами.
  Но в ui программах список это как правило именно то, что показывается на экране. А то, что хранится внутри
  другое по сути. Вся эта игра в представления, модели и прочее сослужила недобрую службу. Вещи стали не вещами,
  чёрт знает чем. Вы не можете просто взять и передать список. Вот допустим если список в формате org, то можно
  передать его. Но его отобразить ещё надо будет. Хотя можно и простым текстовым просмотрщиком посмотреть, это всё
  же будет не то. То есть получается то, что вы передаёте это не то, что имеете. Да, пересказывая мысленный
  список дело обстоит подобным образом. Но там хорошо то, что человек вас понимает, то есть у него сразу же
  есть весь инструментарий для принятия. А вот передавая человеку список по почте в каком-либо формате вы
  только надеятесь, что раз уж это pdf, то уж в 99% случаев человек список просмотрит. Является ли при этом
  pdf вещью? Нет. А должен ли? А это вопрос.
  Прежде всего передать - это процесс. Это не просто взял и отправил человеку на епочту нечто, нет.
  Это значит также принятие. То есть когда ты передаёшь, ты знаешь, что кто-то сможет понять то, что ты
  передал. Поэтому передача это двусторонний процесс: ты дал, он взял.

+ изменять - это
  Вот тут самое интересное. Большинство современных компьютерных способов передачи данных вообще не расчитаны
  на то, чтобы потом что-то изменять. Тут конечно мне возразят и вспомнят про офисные форматы вроде таблиц
  текстовых документов. Да, такое исключение имеет место быть. Однако большинство людей также знает, насколько
  тут всё не так просто. И каковы гарантии, что полученный документ будет способен редактироваться? Тут много
  нюансов. А почему? Да потому что да, концепцию документов то создали, но концепции их потребления - нету.
  Получается что изменять - это как выйдет, как повезёт. Но если не рассчитывать на везение, то надо просто
  договориться с принимающей стороной о версии софта и тогда всё ок. А это значит, что изменять это также процесс,
  как передача. Вы формируете список, договариваетесь о нюансах с принимающей стороной, что он сможет работать
  с тем, что вы передаёте.

Как мы видим все четыре пункта очень тесно связаны друг с другом. При этом первые два пункта формируют то, что
я бы назвал - вещь. А последние два пункта - это действия, связанные с этой вещью. Эти действия могут совершать
некоторые, ну скажем, актёры. Итого запишем это для начала так:

* macro, grammar. не совсем к теме natural, но не плодить же проекты:)
  Уже достаточно давно я пришёл к вывоводу, что С мне достаточно для всего, но он мне кажется слишком
  низкоуровневым. При этом его низкоуровневость часто мне нужна, просто хочется чтобы также частно можно было
  использовать высокоуровневые конструкции прямо в С. Попытаюсь сформулировать в этой статье о чём речь.
  Допустим у нас есть некоторый файл с простым json:
  simple.json
  {
      "name" : "erunda",
      "data" : "arbrakadabra"
  }

  Теперь мы хотели бы работать из С с этим json, с минимальными усилиями, но и с максимальным контролем:

  json simple = file.load('simple.json');
  printf("name is %s, data is %s\n", simple.name, simple.data);
  delete simple;
  
  Вполне себе как на С++ так ведь? 
* мысли на тему форта, слов и тд
  ***print***
  написать привет мир в общий журнал
  write 'hello world' in log console
  
  **crontab_handler***
  разобрать json, взять из него 'каждый' и записать в публикатор времени
  parse json, get each from this and write time in time printer
  
  ***read_timer***
  прочитай кронтаб и сообщи обработчику кронтаба
  to read 'crontab' file and message to crontab_handler
  
  timer to run each 10 and message to 'print_timer'
  таймер работай каждые 10 и сообщай 'print_timer'

  timer to run each 100 and message to 'read_timer'
  таймер работай каждые 100 и сообщай 'read_timer'


